      name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Run steps from repo root (since Makefile is at the root)
    defaults:
      run:
        shell: bash
        working-directory: .

    env:
      # Use the mapped Postgres port from the service
      DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
      TZ: UTC
      CI: "true"
      # Example secrets (move any secrets to GitHub → Repo Settings → Secrets and variables → Actions)
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      # Add other needed secrets here (example):
      # REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: nudgepay/requirements.txt

      - name: Install system deps (optional)
        run: |
          sudo apt-get update -y
          # Add OS packages here if your project needs them, otherwise keep it minimal.

      - name: Make CI (fmt, lint, typecheck, tests)
        run: make ci

      # (Optional) Upload pytest results or coverage artifacts
      # - name: Upload coverage
      #   if: success() || failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage
      #     path: nudgepay/htmlcov
