app = "nudgepay-app"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  BASE_URL = "https://nudgepay-app.fly.dev"
  DATABASE_URL = "sqlite:////data/nudgpay.db"
  SESSION_HTTPS_ONLY = "true"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "data"
  destination = "/data"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
